name: Deploy CV to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  #--- TAHAPAN CI (Continuous Integration) ---
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Cek Apakah File index.html Ada (Automated Test)
        run: test -f index.html

  #--- TAHAPAN CD (Continuous Deployment) ---
  deploy-to-pages:
    needs: build-and-test # CD hanya jalan jika CI di atas sukses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy ke GitHub Pages (Otomatis Berubah)
        id: deployment
        uses: actions/deploy-pages@v4